defaults:
  ask_before_kill: true
  reuse_workspaces: true

hardware_profiles:
  battery:
    disable_modes: [gaming]
  plugged:
    allow_all: true

modes:
  browsing:
    label: "Browse and Chill"
    firefox:
      profile: chill
    workspaces:
      1:
        - firefox
      2:
        - ytmdesktop

  work:
    label: "Work / Research"
    firefox:
      profile: research
    workspaces:
      1:
        - firefox
        - obsidian
        - zotero
      2:
        - vscode: "~/Work/ResearchExperiment.code-workspace"
        - terminal
      3:
        - gnome-pomodoro
        - ytmdesktop

  gaming:
    label: "Gaming"
    workspaces:
      1:
        - lutris
        - steam
      2:
        - discord:
            server: none
            background: true

  contributor:
    label: "Contributor Mode"
    firefox:
      profile: contributor
      urls:
        - https://github.com/
    workspaces:
      1:
        - firefox
      2:
        - vscode: "~/Work/Contributor.code-workspace"
      3:
        - discord:
            server: HF2P